select * from cleaned_playstore_apps
--1. Which apps have the highest rating in the given available dataset?
select App, rating from cleaned_playstore_apps where rating > 4.9

--2. What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
select app, installs, reviews from cleaned_playstore_apps where rating > 4.9

--3. Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
select app, category, reviews from cleaned_playstore_apps
select max(reviews) from cleaned_playstore_apps
select reviews, category, app from cleaned_playstore_apps where reviews = '9992.0'

--4. What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps  from the google play store, the amount is considered in the revenue0)
alter table cleaned_playstore_apps alter column price float
select sum(price) as total_revenue from cleaned_playstore_apps 

--5. Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
alter table cleaned_playstore_apps alter column installs float
select category, max(installs) as max_installs from cleaned_playstore_apps group by Category
select max(installs) as max_installs from cleaned_playstore_apps
select category from cleaned_playstore_apps where installs = 1000000000

--6.Which Genre has the most number of published apps?
select app, Genres from cleaned_playstore_apps
select genres, count(genres) as genre_count 
from cleaned_playstore_apps group by genres order by genre_count desc
select top 1 genres from cleaned_playstore_apps where genres = 'Tools'

--7. Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
--(to avoid duplicate results use distinct)
select distinct app, installs, category from cleaned_playstore_apps where (Category = 'GAME' and Installs =1000000000)
select max(installs) from cleaned_playstore_apps where Category = 'GAME' 

--8. Provide the list of apps that can work on android version 4.0.3 and UP.
select app, [Android Ver] from cleaned_playstore_apps where [Android Ver] = '4.0.3 and up'

--9. How many apps from the given data set are free? Also, provide the number of paid apps.
select count(type) as num_free_apps from cleaned_playstore_apps where Type = 'free'

select count(type) as num_paid_apps from cleaned_playstore_apps where Type = 'paid'

--10. Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
alter table cleaned_playstore_apps alter column reviews float
select app, reviews from cleaned_playstore_apps where Category= 'dating'
select max(reviews) as highest_reviews_dating from cleaned_playstore_apps where Category= 'dating'
select app, reviews from cleaned_playstore_apps where (Reviews = 516917 and Category='dating')

select app, max(reviews) from cleaned_playstore_apps where Category = 'dating' group by app